-- Generated from questionBank.ts on 2026-05-18T15:56:43.709Z
-- This ensures frontend and backend questions are synchronized

DELETE FROM questions;

INSERT INTO questions (question_id, section_id, question_text) VALUES
  ('intime-1', 'intime', 'Quelle partie du corps de ton partenaire t''attire le plus'),
  ('intime-2', 'intime', 'Combien de temps pourrais tu rester sans relations sexuelles'),
  ('intime-3', 'intime', 'Quel est ton plus grand fantasme non realise'),
  ('intime-4', 'intime', 'Comment ton partenaire sait il que tu as envie'),
  ('intime-5', 'intime', 'Quelle sensation te fait perdre le controle'),
  ('intime-6', 'intime', 'T''es tu deja arousee par ton partenaire juste en le regardant'),
  ('intime-7', 'intime', 'Quelle position vous preferez'),
  ('intime-8', 'intime', 'As tu deja eu des pensees sexuelles durant votre premiere rencontre'),
  ('intime-9', 'intime', 'Que fais tu quand tu as envie et que ton partenaire n''a pas le temps'),
  ('intime-10', 'intime', 'Combien de fois par semaine vous aimeriez faire l amour'),
  ('intime-11', 'intime', 'T''as deja imagine ton partenaire avec quelqu''un d''autre'),
  ('intime-12', 'intime', 'Quel type de baiser t''excite le plus'),
  ('intime-13', 'intime', 'Tu preferes quand l initiative vient'),
  ('intime-14', 'intime', 'As tu jamais fini en larmes apres'),
  ('intime-15', 'intime', 'Ton partenaire te connaît il vraiment sexuellement'),
  ('intime-16', 'intime', 'T''aimerais essayer quelque chose de nouveau que ton partenaire ignore'),
  ('intime-17', 'intime', 'A quel moment de la journee es tu la plus excitee'),
  ('intime-18', 'intime', 'Quel est ton plus beau souvenir intime avec ton partenaire'),
  ('intime-19', 'intime', 'Tu as deja eu honte apres un moment intime'),
  ('intime-20', 'intime', 'Combien de temps vous parlez apres'),
  ('intime-21', 'intime', 'Y a t il quelque chose que tu n''oserais jamais demander'),
  ('intime-22', 'intime', 'Tu trouves ton corps'),
  ('intime-23', 'intime', 'Ton partenaire t''a deja surprise sexuellement'),
  ('intime-24', 'intime', 'Comment tu aimes etre touchee au debut'),
  ('intime-25', 'intime', 'T''as deja fini plus excitee qu''au debut'),
  ('intime-26', 'intime', 'Quelle est ta fantaisie avec ton partenaire'),
  ('intime-27', 'intime', 'Tu aimes recevoir ou donner du plaisir'),
  ('intime-28', 'intime', 'Ton desir pour ton partenaire'),
  ('intime-29', 'intime', 'Tu preferes quand c est'),
  ('intime-30', 'intime', 'Tes attentes sexuelles avec ton partenaire'),
  ('intime-31', 'intime', 'Tu as deja simule le plaisir'),
  ('intime-32', 'intime', 'Quelle est l''une de tes limites dures'),
  ('intime-33', 'intime', 'Tu aimes les jeux de seduction avant'),
  ('intime-34', 'intime', 'Tes experiences avant ton partenaire'),
  ('intime-35', 'intime', 'Tu trouves l''idee de dominer'),
  ('intime-36', 'intime', 'Tu trouves l''idee d''etre dominee'),
  ('intime-37', 'intime', 'Le sexe pour toi c''est surtout'),
  ('intime-38', 'intime', 'Tu te masturbes'),
  ('intime-39', 'intime', 'Tu aimes regarder du contenu adulte'),
  ('intime-40', 'intime', 'Ton partenaire sait il ce qui te fait vraiment plaisir'),
  ('intime-41', 'intime', 'Tu aimes l''idee de faire l''amour en public'),
  ('intime-42', 'intime', 'Tes pensees pendant l''acte sont'),
  ('intime-43', 'intime', 'Le meilleur compliment qu''on t''ait fait'),
  ('intime-44', 'intime', 'Ton partenaire a deja demande quelque chose d''un peu tabu'),
  ('intime-45', 'intime', 'L''une de tes fantasies implique'),
  ('intime-46', 'intime', 'Tu veux toujours plus ou tu es satisfaite'),
  ('intime-47', 'intime', 'Ton niveau d orgasme avec ton partenaire'),
  ('intime-48', 'intime', 'Le sexe vous rapproche'),
  ('intime-49', 'intime', 'Tu aimes quand il/elle prend les devants'),
  ('intime-50', 'intime', 'Tes craintes concernant le sexe'),
  ('intime-51', 'intime', 'Tu as deja teste des accessoires'),
  ('intime-52', 'intime', 'Apres combien de temps vous vous etes touches'),
  ('intime-53', 'intime', 'Ton partenaire t''a surpris sexuellement'),
  ('intime-54', 'intime', 'Quel moment de la semaine vous preferez'),
  ('intime-55', 'intime', 'Tu controles ou tu laisses faire'),
  ('intime-56', 'intime', 'Tes reves erotiques impliquent'),
  ('intime-57', 'intime', 'Tu as deja refuse une avance'),
  ('intime-58', 'intime', 'Quand tu vois ton partenaire tu penses'),
  ('intime-59', 'intime', 'Ton partenaire comprend tes besoins sexuels'),
  ('intime-60', 'intime', 'Vous utilisez des contraceptifs'),
  ('intime-61', 'intime', 'L''une de vos plus belles connexions'),
  ('intime-62', 'intime', 'Tu aimes avoir l''impression de decouvrir ton partenaire'),
  ('intime-63', 'intime', 'Votre sexualite s''est intensifiee'),
  ('intime-64', 'intime', 'Tu aimes parler pendant'),
  ('intime-65', 'intime', 'Tes insecurites corporelles'),
  ('intime-66', 'intime', 'Ton partenaire t''a deja blessee émotionnellement apres'),
  ('intime-67', 'intime', 'Tu te compares a ses experiences passees'),
  ('intime-68', 'intime', 'Votre frequence est'),
  ('intime-69', 'intime', 'Tu as essaye de nouvelles positions'),
  ('intime-70', 'intime', 'Ton partenaire ecoute tes limites'),
  ('intime-71', 'intime', 'Au debut vous aviez'),
  ('intime-72', 'intime', 'L''orgasme est pour toi'),
  ('intime-73', 'intime', 'Tu imagines votre futur sexuel'),
  ('intime-74', 'intime', 'Vous discutez apres d''ameliorations'),
  ('intime-75', 'intime', 'Tu te vois faire l''amour avec lui/elle longtemps'),
  ('intime-76', 'intime', 'L''une de tes plus grandes satisfactions'),
  ('intime-77', 'intime', 'Tu as deja ete en plaisir continu'),
  ('intime-78', 'intime', 'Ton lien physique avec ton partenaire'),
  ('intime-79', 'intime', 'Tu aimerais plus d''adventure sexuelle'),
  ('intime-80', 'intime', 'Ton corps redit t''arouse'),
  ('intime-81', 'intime', 'Vous etes a l''aise de vous voir completement'),
  ('intime-82', 'intime', 'Tes fantasmes evoluent avec'),
  ('intime-83', 'intime', 'Apres vous vous sentez'),
  ('intime-84', 'intime', 'Ton partenaire te rend'),
  ('intime-85', 'intime', 'Vous avez des codes sexuels'),
  ('intime-86', 'intime', 'Tes prejuges sexuels'),
  ('intime-87', 'intime', 'Votre chimie sexuelle'),
  ('intime-88', 'intime', 'Tu aimes l''idee de masturbation mutuelle'),
  ('intime-89', 'intime', 'La confiance sexuelle vient'),
  ('intime-90', 'intime', 'Vous parlez de vos experiences passees'),
  ('intime-91', 'intime', 'L''une de tes reveries implique'),
  ('intime-92', 'intime', 'Tu regardes ton partenaire pendant'),
  ('intime-93', 'intime', 'Le sexe change votre relation'),
  ('intime-94', 'intime', 'Tes moments les plus vulnerables'),
  ('intime-95', 'intime', 'Votre consommation de contenu adulte'),
  ('intime-96', 'intime', 'Vous parlez de sexe ensemble'),
  ('intime-97', 'intime', 'Ton rapport au plaisir est'),
  ('intime-98', 'intime', 'Si tu pouvais changer une chose'),
  ('intime-99', 'intime', 'Vous avez une vraie complicite sexuelle'),
  ('intime-100', 'intime', 'Ton partenaire connait tes vrais besoins')
ON CONFLICT (question_id) DO UPDATE SET
  section_id = EXCLUDED.section_id,
  question_text = EXCLUDED.question_text;
