-- Synchronize questions with the "Complicité & Désirs" theme from frontend
-- This replaces the previous explicitly sexual questions with a more inclusive set

DELETE FROM questions;

INSERT INTO questions (question_id, section_id, question_text) VALUES
  ('intime-1', 'intime', 'Quelle est la première dispute ridicule dont on rigole aujourd''hui ?'),
  ('intime-2', 'intime', 'Si notre histoire était un livre, quel titre donnerais-tu au premier chapitre ?'),
  ('intime-3', 'intime', 'Quel est le message textuel (SMS) de ma part que tu as gardé en mémoire ?'),
  ('intime-4', 'intime', 'Te souviens-tu du premier restaurant où l''on a mangé ensemble ?'),
  ('intime-5', 'intime', 'Quelle est la plus grande surprise que je t''ai faite (ou tenté de te faire) ?'),
  ('intime-6', 'intime', 'À quel moment as-tu été le plus fier ou la plus fière de moi ?'),
  ('intime-7', 'intime', 'Si on devait résumer notre année passée en un seul mot, ce serait lequel ?'),
  ('intime-8', 'intime', 'Quel geste tout simple de ma part te fait rougir ou t''intimide encore ?'),
  ('intime-9', 'intime', 'L''endroit le plus insolite où tu aimerais qu''on s''embrasse ?'),
  ('intime-10', 'intime', 'Quelle est la première chose que tu as remarquée chez moi ?'),
  ('intime-11', 'intime', 'Une chanson qui te fait instantanément penser à nous deux ?'),
  ('intime-12', 'intime', 'Quelle odeur te rappelle immédiatement ma présence ?'),
  ('intime-13', 'intime', 'À quel moment précis as-tu su que tu avais des sentiments pour moi ?'),
  ('intime-14', 'intime', 'Quelle qualité chez moi t''apaise le plus quand tu es stressé(e) ?'),
  ('intime-15', 'intime', 'Un trait de mon caractère que tu as appris à aimer avec le temps ?'),
  ('intime-16', 'intime', 'Si on partait en voyage demain sans destination, où irais-tu avec moi ?'),
  ('intime-17', 'intime', 'Quelle est ta façon préférée de recevoir de l''affection quand on est en public ?'),
  ('intime-18', 'intime', 'Le compliment le plus touchant que je t''ai fait ?'),
  ('intime-19', 'intime', 'Qu''est-ce qui te manque le plus chez moi quand on est séparés quelques jours ?'),
  ('intime-20', 'intime', 'Quel est le souvenir le plus absurde qu''on partage ?'),
  ('intime-21', 'intime', 'Une habitude chez moi que tu trouves secrètement adorable ?'),
  ('intime-22', 'intime', 'Si on devait créer un rituel rien qu''à nous, ce serait quoi ?'),
  ('intime-23', 'intime', 'Le moment où tu t''es senti(e) le plus en sécurité avec moi ?'),
  ('intime-24', 'intime', 'Quel type de baiser te fait perdre tes moyens ?'),
  ('intime-25', 'intime', 'Ton envie la plus ''folle'' mais légère pour nous deux ?'),
  ('intime-26', 'intime', 'Ce que tu trouves le plus attirant dans mon regard ?'),
  ('intime-27', 'intime', 'Quelle partie de mon corps est pour toi ''interdite'' ou mystérieuse ?'),
  ('intime-28', 'intime', 'L''idée d''un baiser volé en public te provoque quoi ?'),
  ('intime-29', 'intime', 'Quel vêtement que je porte te rend le plus nerveux/se ?'),
  ('intime-30', 'intime', 'Si tu devais me décrire avec un seul adjectif ''épicé'', lequel choisirais-tu ?'),
  ('intime-31', 'intime', 'Quel est le compliment le plus osé que tu aimerais me faire ?'),
  ('intime-32', 'intime', 'Un fantasme léger que tu n''as jamais osé me mentionner ?'),
  ('intime-33', 'intime', 'Comment décrirais-tu la tension entre nous quand on se regarde sans parler ?'),
  ('intime-34', 'intime', 'Ce qui te fait craquer instantanément chez moi ?'),
  ('intime-35', 'intime', 'L''endroit où tu préfères être touché(e) pour te détendre ?'),
  ('intime-36', 'intime', 'Une chose ''gênante'' mais excitante que tu aimerais essayer ?'),
  ('intime-37', 'intime', 'Ton premier souvenir ''électrique'' avec moi ?'),
  ('intime-38', 'intime', 'Ce que tu penses quand je te regarde avec un petit sourire en coin ?'),
  ('intime-39', 'intime', 'Si on devait s''échapper pour une heure, on irait où ?'),
  ('intime-40', 'intime', 'La sensation la plus intense que tu associes à moi ?'),
  ('intime-41', 'intime', 'Quelle est la chose la plus courageuse que tu as faite par amour pour moi ?'),
  ('intime-42', 'intime', 'Le moment où tu t''es dit ''C''est elle/lui'' ?'),
  ('intime-43', 'intime', 'Quelle chanson définirait parfaitement notre premier rendez-vous ?'),
  ('intime-44', 'intime', 'Ce que tu préfères dans nos silences ensemble ?'),
  ('intime-45', 'intime', 'L''aspect de ma personnalité qui te surprend le plus au quotidien ?'),
  ('intime-46', 'intime', 'Si on devait voyager dans le temps, à quelle étape de nous deux voudrais-tu retourner ?'),
  ('intime-47', 'intime', 'Quelle est la petite attention que je fais et qui te touche sans que je le sache ?'),
  ('intime-48', 'intime', 'Ton rêve le plus fou pour notre futur ensemble ?'),
  ('intime-49', 'intime', 'Ce que tu as ressenti la première fois qu''on s''est tenus la main ?'),
  ('intime-50', 'intime', 'L''endroit où tu te sens le plus ''nous'' ?'),
  ('intime-51', 'intime', 'Quelle est la valeur que nous partageons et qui est la plus importante pour toi ?'),
  ('intime-52', 'intime', 'Si tu pouvais voler une seule qualité chez moi, laquelle serait-ce ?'),
  ('intime-53', 'intime', 'Le souvenir le plus apaisant que tu as de nous ?'),
  ('intime-54', 'intime', 'L''expression de mon visage qui te fait le plus rire ?'),
  ('intime-55', 'intime', 'Si on devait s''échanger les rôles pour une journée, qu''est-ce qui te ferait le plus peur ?'),
  ('intime-56', 'intime', 'La chose la plus folle qu''on ait faite ensemble ?'),
  ('intime-57', 'intime', 'Quelle est la phrase que je dis tout le temps et que tu adores (ou détestes) ?'),
  ('intime-58', 'intime', 'Comment décrirais-tu notre complicité à quelqu''un qui ne nous connaît pas ?'),
  ('intime-59', 'intime', 'Le moment où tu as senti que notre lien a changé de dimension ?'),
  ('intime-60', 'intime', 'Quelle est la promesse (même petite) qu''on a faite et que tu n''oublieras jamais ?'),
  ('intime-61', 'intime', 'Ton premier réflexe quand tu penses à moi au réveil ?'),
  ('intime-62', 'intime', 'L''objet banal qui te rappelle moi dès que tu le vois ?'),
  ('intime-63', 'intime', 'Si on devait écrire notre propre dictionnaire, quel serait le mot le plus important ?'),
  ('intime-64', 'intime', 'Quelle est la chose la plus courageuse que tu as faite pour protéger notre relation ?'),
  ('intime-65', 'intime', 'Ce que tu préfères dans la façon dont on gère nos désaccords ?'),
  ('intime-66', 'intime', 'Ton moment préféré quand on est juste tous les deux, sans écrans ?'),
  ('intime-67', 'intime', 'Quelle est la qualité chez moi que tu aimerais avoir pour toi-même ?'),
  ('intime-68', 'intime', 'Le souvenir le plus drôle qu''on a d''un rendez-vous raté ?'),
  ('intime-69', 'intime', 'Si on devait s''installer dans un endroit imaginaire, ce serait quoi ?'),
  ('intime-70', 'intime', 'Qu''est-ce qui te fait dire ''Ça, c''est vraiment [Moi]'' ?'),
  ('intime-71', 'intime', 'La première impression que tu as eue de moi, et comment elle a changé ?'),
  ('intime-72', 'intime', 'Ton moment préféré de la journée quand on est ensemble ?'),
  ('intime-73', 'intime', 'Si on devait apprendre une nouvelle activité ensemble, ce serait quoi ?'),
  ('intime-74', 'intime', 'Qu''est-ce qui te rend le plus fier/fière de notre couple ?'),
  ('intime-75', 'intime', 'Le petit rituel secret qu''on a et que personne d''autre ne connaît ?'),
  ('intime-76', 'intime', 'Ce que tu préfères dans la façon dont on se soutient ?'),
  ('intime-77', 'intime', 'La chose la plus mignonne que j''ai faite sans m''en rendre compte ?'),
  ('intime-78', 'intime', 'L''endroit où tu te sens le plus aimé(e) avec moi ?'),
  ('intime-79', 'intime', 'Si on devait s''offrir un cadeau sans limite de budget, tu voudrais quoi ?'),
  ('intime-80', 'intime', 'Le souvenir le plus vibrant d''un moment de tendresse ?'),
  ('intime-81', 'intime', 'Ce qui te rend le plus optimiste pour notre futur ?'),
  ('intime-82', 'intime', 'Quelle est la leçon la plus précieuse que tu as apprise à mes côtés ?'),
  ('intime-83', 'intime', 'L''aspect de notre relation que tu protégerais le plus ?'),
  ('intime-84', 'intime', 'Si on devait résumer notre premier baiser en un mot ?'),
  ('intime-85', 'intime', 'Le moment où tu as senti que tu pouvais être totalement toi-même avec moi ?'),
  ('intime-86', 'intime', 'Quelle est la chose la plus folle qu''on pourrait faire ensemble l''année prochaine ?'),
  ('intime-87', 'intime', 'Ce qui te manque le plus quand on ne s''est pas vus de la journée ?'),
  ('intime-88', 'intime', 'L''expression de mon visage qui te fait craquer à coup sûr ?'),
  ('intime-89', 'intime', 'Si on devait choisir un animal pour représenter notre couple, lequel serait-ce ?'),
  ('intime-90', 'intime', 'Le geste le plus romantique que j''ai fait sans le vouloir ?'),
  ('intime-91', 'intime', 'L''idée de m''embrasser sous la pluie te provoque quoi ?'),
  ('intime-92', 'intime', 'Quel est ton ''point faible'' quand je m''approche de toi ?'),
  ('intime-93', 'intime', 'Une tenue que je porte et qui te rend instantanément nerveux/se ?'),
  ('intime-94', 'intime', 'L''endroit le plus audacieux où tu aimerais qu''on se retrouve ?'),
  ('intime-95', 'intime', 'Si on devait jouer à un jeu de rôle léger, quel personnage choisirais-tu pour moi ?'),
  ('intime-96', 'intime', 'Ce que tu préfères quand on s''embrasse pour la première fois de la journée ?'),
  ('intime-97', 'intime', 'Une chose ''interdite'' mais légère que tu aimerais qu''on tente ?'),
  ('intime-98', 'intime', 'Le compliment le plus osé que tu n''as jamais osé me faire ?'),
  ('intime-99', 'intime', 'L''idée de me voir rougir te provoque quoi ?'),
  ('intime-100', 'intime', 'Si tu devais résumer notre tension actuelle en un mot ?');
